name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and push Docker image to Github Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag,enable=${{ github.event_name != 'workflow_dispatch' }}
            type=raw,value=latest

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          load: true
          files: .github/workflows/docker/docker-bake.hcl
      
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@0.3.1
        with:
          inputs: misskey:amd64,misskey:arm64
          images: ${{ steps.meta.outputs.tags }}
          push: true
