name: Publish Docker image (develop)

on:
  push:
    branches:
      - taiyme
  workflow_dispatch:

jobs:
  build:
    name: Build latest images
    uses: ./.github/workflows/docker-build.yml
    with:
      tags: |
        develop
