name: Publish Docker image (release)

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build latest images
    uses: ./.github/workflows/docker-build.yml
    with:
      tags: |
        type=edge
        type=ref,event=pr
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
