name: Pull Request Labeler

on:
  pull_request_target:

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_SECRET }}

      - uses: actions/labeler@v5
        with:
          repo-token: ${{ steps.app-token.outputs.token }}
          configuration-path: .github/labeler.yaml
          sync-labels: true
