name: Make Release

on:
  pull_request:
    branches:
      - release
    types:
      - labeled

jobs:
  check_pr:
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - name: Check release actor
        if: github.actor != github.repository_owner
        run: |
          echo "::error::Only repository owner can create releases."
          exit 1

      - name: Check release label
        if: github.event.label.name != 'release'
        run: |
          echo "::error::You need to specify the 'release' label to create releases."
          exit 1

  get_new_version:
    name: Get new version
    runs-on: ubuntu-latest
    needs:
      - check_pr
    outputs:
      version: ${{ steps.new_version.outputs.NEW_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        run: |
          git fetch --prune
          echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Get prev base version
        run: echo "PREV_BASE_VERSION=$(echo ${{ env.LATEST_TAG }} | cut -d- -f1)" >> $GITHUB_ENV

      - name: Get next base version
        run: echo "NEXT_BASE_VERSION=$(jq -r '.version' '${{ github.workspace }}/package.json' | cut -d- -f1)" >> $GITHUB_ENV

      - name: Reset revision
        if: env.PREV_BASE_VERSION != env.NEXT_BASE_VERSION
        run: echo 'REVISION=0' >> $GITHUB_ENV

      - name: Update revision
        if: env.PREV_BASE_VERSION == env.NEXT_BASE_VERSION
        run: echo "REVISION=$(($(echo ${{ env.LATEST_TAG }} | cut -d- -f2 | cut -d. -f2) + 1))" >> $GITHUB_ENV

      - name: Build new version
        id: new_version
        run: echo 'NEW_VERSION=${{ env.NEXT_BASE_VERSION }}-taiyme.${{ env.REVISION }}' >> $GITHUB_OUTPUT

  update_package_json:
    name: Update package.json
    runs-on: ubuntu-latest
    needs:
      - get_new_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update package.json
        run: jq '.version = "${{ needs.get_new_version.outputs.version }}"' '${{ github.workspace }}/package.json' --tab > tmp && mv tmp '${{ github.workspace }}/package.json'

      - name: Upload package.json
        uses: actions/upload-artifact@v3
        with:
          name: version_files
          path: ${{ github.workspace }}/package.json

  update_package_json_misskey_js:
    name: Update package.json (misskey-js)
    runs-on: ubuntu-latest
    needs:
      - get_new_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update package.json (misskey-js)
        run: jq '.version = "${{ needs.get_new_version.outputs.version }}"' '${{ github.workspace }}/packages/misskey-js/package.json' --tab > tmp && mv tmp '${{ github.workspace }}/packages/misskey-js/package.json'

      - name: Upload package.json (misskey-js)
        uses: actions/upload-artifact@v3
        with:
          name: version_files
          path: ${{ github.workspace }}/packages/misskey-js/package.json

  update_docker_compose_yml:
    name: Update compose.yml
    runs-on: ubuntu-latest
    needs:
      - get_new_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update compose.yml
        run: yq eval '.services.web.image = "ghcr.io/${{ github.repository }}:${{ needs.get_new_version.outputs.version }}"' -i '${{ github.workspace }}/compose_example.yml'

      - name: Upload compose.yml
        uses: actions/upload-artifact@v3
        with:
          name: version_files
          path: ${{ github.workspace }}/compose_example.yml

  commit_tag_push:
    name: Commit, Tag and Push
    needs:
      - get_new_version
      - update_package_json
      - update_package_json_misskey_js
      - update_docker_compose_yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: version_files

      - name: Check change
        id: is_chnage
        run: echo "is_change=$(git status -s | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit and Tag
        if: steps.is_chnage.outputs.is_change != '0'
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'Release: ${{ needs.get_new_version.outputs.version }}'
          git tag '${{ needs.get_new_version.outputs.version }}'
          git push origin HEAD --follow-tags

  merge_pr:
    name: Merge PR
    needs:
      - commit_tag_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          gh pr merge ${{ github.event.pull_request.number }} --merge

  release:
    name: Release
    needs:
      - get_new_version
      - merge_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.get_new_version.outputs.version }}
          body: ${{ github.event.pull_request.body }}
